# Generated by Django. Editado a mano en un punto: el nombre de la tabla.
#
# `db_table` lleva el esquema de Postgres dentro, y ese esquema cambia por
# entorno (DB_SCHEMA). Si se dejara el literal que genera makemigrations, esta
# migracion solo valdria para el entorno donde se genero, y en el otro Django
# detectaria un cambio de modelo en cada arranque. Por eso se calcula igual que
# en services/imports/models.py.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.config import DB_SCHEMA


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('module', models.CharField(choices=[('subs_subscriptions', 'Subscriptions - Suscripciones'), ('subs_logs', 'Subscriptions - Logs'), ('subs_analysis', 'Subscriptions - Calculo de metricas'), ('crm', 'CRM Analytics - Odoo Export'), ('crm_analysis', 'CRM Analytics - Calculo de metricas'), ('support', 'Support - Tickets'), ('support_analysis', 'Support - Calculo de metricas'), ('subs_lifetime', 'Subscriptions - Ciclo de vida')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('rows_processed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('error', 'Error'), ('warning', 'Advertencia')], default='success', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': f'"{DB_SCHEMA}"."import_action_logs"' if DB_SCHEMA else 'import_action_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
