# Generated by Django. Editado a mano en un punto: el nombre de la tabla.
#
# `db_table` lleva el esquema de Postgres dentro, y ese esquema cambia por
# entorno (DB_SCHEMA). Si se dejara el literal que genera makemigrations, esta
# migracion solo valdria para el entorno donde se genero, y en el otro Django
# detectaria un cambio de modelo en cada arranque. Por eso se calcula igual que
# en services/imports/models.py.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.config import DB_SCHEMA


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('subs_subscriptions', 'Subscriptions - Suscripciones'), ('subs_logs', 'Subscriptions - Logs'), ('subs_analysis', 'Subscriptions - Calculo de metricas'), ('crm', 'CRM Analytics - Odoo Export'), ('crm_analysis', 'CRM Analytics - Calculo de metricas'), ('support', 'Support - Tickets'), ('support_analysis', 'Support - Calculo de metricas'), ('subs_lifetime', 'Subscriptions - Ciclo de vida')], max_length=50)),
                ('periodo', models.CharField(blank=True, default='', max_length=7)),
                ('status', models.CharField(choices=[('pending', 'En cola'), ('running', 'En ejecucion'), ('success', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('log', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('progress_done', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(default=0)),
                ('progress_label', models.CharField(blank=True, default='', max_length=120)),
                ('username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': f'"{DB_SCHEMA}"."analysis_jobs"' if DB_SCHEMA else 'analysis_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'status'], name='analysis_jobs_mod_est_idx')],
            },
        ),
    ]
