# Generated by Django 6.1.1 on 2026-09-11 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'coordinador',
                'verbose_name_plural': 'coordinadores',
                'db_table': 'catalogo_coordinadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
                'db_table': 'catalogo_estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('orden', models.IntegerField(default=999)),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'db_table': 'catalogo_sites',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tarifa', models.CharField(blank=True, default='', max_length=150)),
                ('tecnologia', models.CharField(choices=[('FTTH', 'FTTH (fibra)'), ('RF', 'RF (radiofrecuencia)'), ('GPON', 'GPON')], default='FTTH', max_length=10)),
                ('tipo_persona', models.CharField(choices=[('nat', 'Persona natural'), ('PYME', 'Persona juridica / PYME')], default='nat', max_length=10)),
                ('referencia', models.CharField(blank=True, default='', max_length=200)),
                ('tiene_tv', models.BooleanField(default=False)),
                ('datas_mbps', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('declarar_en_eta', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
                'db_table': 'catalogo_planes',
                'ordering': ['nombre', 'tarifa'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'tarifa'), name='catalogo_plan_nombre_tarifa')],
            },
        ),
        migrations.CreateModel(
            name='ProductoIgnorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'producto ignorado',
                'verbose_name_plural': 'productos ignorados',
                'db_table': 'catalogo_productos_ignorados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tecnologia', models.CharField(choices=[('FTTH', 'FTTH (fibra)'), ('RF', 'RF (radiofrecuencia)'), ('GPON', 'GPON')], default='FTTH', max_length=10)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas', to='subscriptions.coordinador')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='subscriptions.estado')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='subscriptions.site')),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zonas',
                'db_table': 'catalogo_zonas',
                'ordering': ['nombre'],
            },
        ),
    ]
