# Generated by Django 6.1.1 on 2026-09-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tecnologia',
            field=models.CharField(choices=[('FTTH', 'FTTH (fibra)'), ('RF', 'RF (radiofrecuencia)')], default='FTTH', max_length=10),
        ),
        migrations.AlterField(
            model_name='zona',
            name='tecnologia',
            field=models.CharField(choices=[('FTTH', 'FTTH (fibra)'), ('RF', 'RF (radiofrecuencia)')], default='FTTH', max_length=10),
        ),
    ]
