# Generated by Django 6.1.1 on 2026-09-09 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_subscriptions', models.BooleanField(default=True)),
                ('can_view_crm', models.BooleanField(default=True)),
                ('can_view_imports', models.BooleanField(default=True)),
                ('can_view_support', models.BooleanField(default=True)),
                ('can_view_subs_analytics', models.BooleanField(default=True)),
                ('can_view_subs_results', models.BooleanField(default=True)),
                ('can_view_subs_lifetime', models.BooleanField(default=True)),
                ('can_view_subs_sales', models.BooleanField(default=True)),
                ('can_view_eta', models.BooleanField(default=True)),
                ('can_view_crm_analytics', models.BooleanField(default=True)),
                ('can_view_crm_results', models.BooleanField(default=True)),
                ('can_view_support_analytics', models.BooleanField(default=True)),
                ('can_view_support_results', models.BooleanField(default=True)),
                ('can_view_imports_subs', models.BooleanField(default=True)),
                ('can_view_imports_crm', models.BooleanField(default=True)),
                ('can_view_imports_support', models.BooleanField(default=True)),
                ('can_view_import_history', models.BooleanField(default=True)),
                ('can_import_data', models.BooleanField(default=False)),
                ('can_run_calculations', models.BooleanField(default=False)),
                ('can_run_lifetime', models.BooleanField(default=False)),
                ('can_manage_eta', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_import_subs', models.BooleanField(default=False)),
                ('can_import_crm', models.BooleanField(default=False)),
                ('can_import_support', models.BooleanField(default=False)),
                ('can_run_subs_analysis', models.BooleanField(default=False)),
                ('can_run_crm_analysis', models.BooleanField(default=False)),
                ('can_run_support_analysis', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_subscriptions', models.BooleanField(default=True)),
                ('can_view_crm', models.BooleanField(default=True)),
                ('can_view_imports', models.BooleanField(default=True)),
                ('can_view_support', models.BooleanField(default=True)),
                ('can_view_subs_analytics', models.BooleanField(default=True)),
                ('can_view_subs_results', models.BooleanField(default=True)),
                ('can_view_subs_lifetime', models.BooleanField(default=True)),
                ('can_view_subs_sales', models.BooleanField(default=True)),
                ('can_view_eta', models.BooleanField(default=True)),
                ('can_view_crm_analytics', models.BooleanField(default=True)),
                ('can_view_crm_results', models.BooleanField(default=True)),
                ('can_view_support_analytics', models.BooleanField(default=True)),
                ('can_view_support_results', models.BooleanField(default=True)),
                ('can_view_imports_subs', models.BooleanField(default=True)),
                ('can_view_imports_crm', models.BooleanField(default=True)),
                ('can_view_imports_support', models.BooleanField(default=True)),
                ('can_view_import_history', models.BooleanField(default=True)),
                ('can_import_data', models.BooleanField(default=False)),
                ('can_run_calculations', models.BooleanField(default=False)),
                ('can_run_lifetime', models.BooleanField(default=False)),
                ('can_manage_eta', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_import_subs', models.BooleanField(default=False)),
                ('can_import_crm', models.BooleanField(default=False)),
                ('can_import_support', models.BooleanField(default=False)),
                ('can_run_subs_analysis', models.BooleanField(default=False)),
                ('can_run_crm_analysis', models.BooleanField(default=False)),
                ('can_run_support_analysis', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('analyst', 'Analista'), ('viewer', 'Visualizador (Solo Lectura)')], default='viewer', max_length=20)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='config.permissiongroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
