# Generated by Django 6.1.1 on 2026-09-09 18:58

from django.db import migrations, models

from core.config import DB_SCHEMA


class Migration(migrations.Migration):
    # `db_table` embebe el esquema, que cambia por entorno: se usa la misma
    # expresion que el modelo en lugar del literal que escribe makemigrations,
    # o la migracion solo valdria en el entorno donde se genero. Mismo motivo
    # que en services/imports/migrations/.
    #
    # El modelo es `managed = False`: esta migracion no crea ninguna tabla, solo
    # deja el estado registrado para que `makemigrations --check` quede limpio.
    # La tabla la crea `manage.py preparar_sesiones`.

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntorno',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'sesion',
                'verbose_name_plural': 'sesiones',
                'db_table': f'"{DB_SCHEMA}"."django_session"' if DB_SCHEMA else 'django_session',
                'managed': False,
            },
        ),
    ]
