# Generated by Django 6.1.1 on 2026-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_sesionentorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='can_manage_catalogos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_catalogos',
            field=models.BooleanField(default=False),
        ),
    ]
