# Generated by Django 6.1.1 on 2026-09-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_cerrar_permisos_de_lectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='can_manage_support_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_support_users',
            field=models.BooleanField(default=False),
        ),
    ]
