# Generated by Django 6.1.1 on 2026-09-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'db_table': 'catalogo_departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_odoo', models.CharField(max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='support.departamento')),
            ],
            options={
                'verbose_name': 'usuario de soporte',
                'verbose_name_plural': 'usuarios de soporte',
                'db_table': 'catalogo_usuarios_soporte',
                'ordering': ['nombre_odoo'],
            },
        ),
    ]
