# Generated by Django 6.1.1 on 2026-09-23 13:08

import django.db.models.deletion
from django.db import migrations, models


def sembrar_historial(apps, schema_editor):
    """Cada usuario ya registrado arranca su historia con el departamento de hoy.

    Sin esta fila, quien existia antes del historial no pertenece a ningun
    departamento en ningun mes. `desde` nulo es "desde el ingreso".
    """
    UsuarioSoporte = apps.get_model("support", "UsuarioSoporte")
    HistorialDepartamento = apps.get_model("support", "HistorialDepartamento")
    HistorialDepartamento.objects.bulk_create(
        HistorialDepartamento(usuario_id=u.pk, departamento_id=u.departamento_id, desde=None)
        for u in UsuarioSoporte.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosoporte',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariosoporte',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='support.departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='support.usuariosoporte')),
            ],
            options={
                'verbose_name': 'cambio de departamento',
                'verbose_name_plural': 'historial de departamentos',
                'db_table': 'catalogo_usuarios_soporte_historial',
                'ordering': [models.OrderBy(models.F('desde'), nulls_first=True), 'id'],
            },
        ),
        migrations.RunPython(sembrar_historial, migrations.RunPython.noop),
    ]
