export { CrmDashboardView } from './components/CrmDashboardView';
export { CrmAnalyticsView } from './components/CrmAnalyticsView';
export { CrmAnalyticsFilters } from './components/analytics/CrmAnalyticsFilters';
export { CrmAnalyticsCharts } from './components/analytics/CrmAnalyticsCharts';
export { CrmAnalyticsTable } from './components/analytics/CrmAnalyticsTable';
export { CrmStageTimeSection } from './components/analytics/CrmStageTimeSection';
export { CRM_ANALYTICS_COLUMNS } from './components/analytics/crmAnalyticsColumns';
export { CrmResultsView } from './components/CrmResultsView';
export { CrmPeriodDetail } from './components/CrmPeriodDetail';
export { CrmPeriodDimensions } from './components/CrmPeriodDimensions';
export { useCrmDashboard } from './hooks/useCrmDashboard';
export { useCrmAnalytics } from './hooks/useCrmAnalytics';
export { useCrmStageTime } from './hooks/useCrmStageTime';
export { useCrmPeriodDimensions } from './hooks/useCrmPeriodDimensions';
export * from './lib/crmAnalyticsDistribution';
export * from './lib/crmEfectividad';
export * from './lib/crmDimensions';
export * from './lib/crmTiempoEtapa';
export type * from './types';
